### PR TITLE
Allows selection by hitting ENTER if neverSubmit is true

### PR DESCRIPTION
**Pull request by jerefrer**
What do you think ? IMHO I don't see why we don't already do this.

### CODE REVIEW

**Comment by knalli** [comment]
Yes, I think that's okay.

**Comment by jerefrer** [comment]
(Just did a bad commit, if you had emails just forget those, another pull request will come ;))

**Comment by jerefrer** [comment]
Ok it's done (the typo was present in the original tests. I replaced it there as well)

**Comment by knalli** [comment]
And thank you!

**Comment by knalli** [comment]
You should make PR only from topic branches, never from master.

Note: If a PR starts from a master, you are probably wrong.

**Comment by jerefrer** [comment]
Yep I just realized that !

Third PR will come in a branch :D

2013/8/5 Jan Philipp notifications@github.com

**Pull request merged**
